name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List directory contents
        run: |
          echo "Root directory:"
          ls -R
          echo "Actions directory:"
          ls -R .github/actions/koko_project

      - name: Run My Custom Action
        uses: ./.github/actions/koko_project
        with:
          name: "Worlds"
