name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run My Custom Action
        uses: ./.github/actions/koko_project
        with:
          name: "World"
