name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la

    - name: Check for package.json
      run: |
        if [ -f "package.json" ]; then
          echo "package.json exists"
          cat package.json
        else
          echo "package.json does not exist"
          echo "Creating a basic package.json"
          npm init -y
        fi

    - name: Install dependencies
      run: npm install

    - name: Run tests (if available)
      run: |
        if npm run | grep -q "test"; then
          npm test
        else
          echo "No test script found in package.json"
        fi
      continue-on-error: true

    - name: Build project (if available)
      run: |
        if npm run | grep -q "build"; then
          npm run build
        else
          echo "No build script found in package.json"
          echo "Creating a sample build output"
          mkdir -p dist
          echo "Sample build output" > dist/sample.txt
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: project-artifacts-${{ matrix.node-version }}
        path: |
          Stam13/
          exampleStam/
      if: always()

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
