name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
      shell: bash

    - name: Check for package.json
      run: |
        if [ -f "package.json" ]; then
          echo "package.json exists"
        else
          echo "package.json does not exist"
          echo "Creating a basic package.json"
          npm init -y
        fi
      shell: bash

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.node-version }}
        path: test-results/
      if: always()

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
      shell: bash

    - name: Check for package.json
      run: |
        if [ -f "package.json" ]; then
          echo "package.json exists"
        else
          echo "package.json does not exist"
          echo "Creating a basic package.json"
          npm init -y
        fi
      shell: bash

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/
      if: success()

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
